#!/bin/sh

dir=$(pwd)
echo "Installing uno-yt-livechat..."
if [ -d "/usr/share/uno-yt-livechat" ]; then
  sudo sh -c " cp $dir/* /usr/share/uno-yt-livechat/ "
else
  sudo sh -c " mkdir /usr/share/uno-yt-livechat; cp $dir/* /usr/share/uno-yt-livechat/ "
fi
cd /usr/share/uno-yt-livechat
sudo sh -c " rm -rf .git; rm README.md; rm config-example.py; cp $dir/.run/yt-livechat /usr/bin"
