#!/bin/sh

dir=$(pwd)
echo "Installing uno-yt-livechat..."
if [ -d "/usr/lib/uno-yt-livechat" ]; then
    cp $dir/*.py /usr/lib/uno-yt-livechat/
    cp $dir/yt-livechat /usr/lib/uno-yt-livechat/
else
    mkdir /usr/lib/uno-yt-livechat
    cp $dir/*.py /usr/lib/uno-yt-livechat/
    cp $dir/yt-livechat /usr/lib/uno-yt-livechat/
fi
cd /usr/lib/uno-yt-livechat
rm config-example.py
cp $dir/bin/yt-livechat /usr/bin
